test

diff --git a/.github/workflows/bot-action.yml b/.github/workflows/bot-action.yml
--- a/.github/workflows/bot-action.yml
+++ b/.github/workflows/bot-action.yml
@@ -106,6 +106,13 @@ jobs:
           COMMENT_DATE: ${{ github.event.comment.created_at }}
           PR_NUMBER: ${{ steps.pr_info.outputs.prNumber }}
         run: |
+            echo "--- Checking remotes ---"
+            git remote -v
+            echo "--- Checking ref on origin (${{ steps.pr_info.outputs.headRepoFullName }}) ---"
+            git ls-remote origin refs/pull/$PR_NUMBER/merge || echo "Ref not found on origin (fork)."
+            echo "--- Checking ref on base (${{ github.repository }}) ---"
+            git ls-remote https://github.com/${{ github.repository }} refs/pull/$PR_NUMBER/merge || echo "Ref not found on base repository."
+            echo "--- Proceeding with fetch ---"
             git fetch origin refs/pull/$PR_NUMBER/merge:refs/remotes/pull/$PR_NUMBER/merge
             git checkout refs/remotes/pull/$PR_NUMBER/merge
             echo "PR_MERGE_SHA: $(git log -1 --format=%H)"
@@ -119,6 +126,18 @@ jobs:
               echo "❌ Last commit on the pull request is newer than the issue comment triggering this run! Abort!";
               exit -1;
             fi
+      - name: Check out PR branch again
+        uses: actions/checkout@v3
+        env: 
+          HEADREPOFULLNAME: ${{ steps.pr_info.outputs.headRepoFullName }}
+          HEADREF: ${{ steps.pr_info.outputs.headRef }}
+        with:
+          # Instead of checking out the base repo, use the contributor's repo name
+          repository: ${{ env.HEADREPOFULLNAME }}
+          ref: ${{ env.HEADREF }}
+          # You may need fetch-depth: 0 for being able to push
+          fetch-depth: 0
+          token: ${{ secrets.bot_token }}
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
